version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=koalabear
  app:
    build: .
    image: oscarnewman/node-app:10
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ['yarn', 'start']
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://root:root@db:5432/koalabear
    links:
      - db
volumes:
  postgres:
